[program:trust-store-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/task-trust-store/htdocs/trust-store.digitizir.com/artisan queue:listen
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
stopwaitsecs=3600
stderr_logfile=/home/task-trust-store/htdocs/trust-store.digitizir.com/worker.err.log
stdout_logfile=/home/task-trust-store/htdocs/trust-store.digitizir.com/worker.out.log
