<?php

namespace App\Jobs;

use App\Models\User;
use App\Services\DashboardService;
use App\Services\NotificationService;
use App\Services\SettingService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class ReportNotificationJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Execute the job.
     */
    public function handle(
        DashboardService $dashboardService,
        NotificationService $notificationService,
        SettingService $settingService
    ): void {
        // Get yesterday's report data
        $report = $dashboardService->getDailyReport();

        // Get all admin users
        $admins = User::admin()->get();

        if ($admins->isEmpty()) {
            Log::warning('No admin users found to send daily sales report');
            return;
        }

        // Build email content
        $subject = 'Daily Sales Report - ' . $report['date'];
        $content = $this->buildReportContent($report, $settingService);

        // Send notification to all admins
        $sentCount = $notificationService->sendBulkEmail(
            users: $admins,
            subject: $subject,
            content: $content,
            ctaText: 'View Dashboard',
            ctaUrl: route('admin.dashboard')
        );

        Log::info("Daily sales report sent to {$sentCount} admin(s) for {$report['date']}");
    }

    /**
     * Build the email content from report data
     *
     * @param array $report
     * @param SettingService $settingService
     * @return string
     */
    protected function buildReportContent(array $report, SettingService $settingService): string
    {
        $content = "Daily Sales Report for {$report['date']}\n\n";
        $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";

        // Summary
        $content .= "📊 SUMMARY\n";
        $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
        $content .= "Total Orders: {$report['orders_count']}\n";
        $content .= "Total Revenue: $" . number_format($report['revenue'], 2) . "\n";
        $content .= "Total Items Sold: {$report['total_items_sold']}\n\n";

        // Orders by Status
        $content .= "📦 ORDERS BY STATUS\n";
        $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
        foreach ($report['orders_by_status'] as $status => $count) {
            $content .= ucfirst($status) . ": {$count}\n";
        }
        $content .= "\n";

        // Top Selling Products
        if (!empty($report['top_selling_products'])) {
            $content .= "🏆 TOP SELLING PRODUCTS\n";
            $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
            $rank = 1;
            foreach ($report['top_selling_products'] as $productId => $data) {
                $revenue = number_format($data['revenue'], 2);
                $content .= "{$rank}. {$data['name']}\n";
                $content .= "   Quantity Sold: {$data['quantity']} | Revenue: \${$revenue}\n";
                $rank++;
            }
            $content .= "\n";
        }

        // All Products Sold
        if (!empty($report['products_sold']) && count($report['products_sold']) > count($report['top_selling_products'])) {
            $content .= "📋 ALL PRODUCTS SOLD\n";
            $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
            foreach ($report['products_sold'] as $productId => $data) {
                $revenue = number_format($data['revenue'], 2);
                $content .= "• {$data['name']}: {$data['quantity']} units (\${$revenue})\n";
            }
            $content .= "\n";
        }

        $appName = $settingService->get('app_name');
        $content .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
        $content .= "This is an automated daily report generated by " . $appName . ".\n";
        $content .= "Click the button below to view the full dashboard.";

        return $content;
    }
}
